### ISSUE TITLE
BootLoader not available

### ISSUE THREAD

**Issue by NicoHood** [shulter/arduino-ide-config#1]
Hi,
your bootloader file is missing in the repo. I guess this repo was just for yourself, I found it via google.

But maybe you can help me:
I want to flash my Arduino Nano with a faster bootloader. I tried 115200 which worked fine. I tried 250k and 500k with precompiled files from blogs and compiled it on my own. Both didnt work, even though I changed the uploading speed. Not sure if my fake FTDI cant handle this speed. However the ide says it uploads with 250k/500k. And 250k works for normal serial monitor with the nightly IDE.

Any idea?

**Comment by shulter** [comment]
I can't help you, "Both didn't work" is not an error message.

**Comment by NicoHood** [comment]
I got stk not in sync errors.

**Comment by shulter** [comment]
I don't know what usb serial converter, OS, avrdude, IDE version etc you are using..  This still doesn't concern my Arduino settings in this repo. Hey I think you might get help in the Arduino forums if you provide sufficient information. I think you know lots about electronics and software already, so please provide the appropriate information. Try arduino.cc!
